In [2]:
import pandas as pd

In [112]:
df=pd.read_excel("C://Users//shesh//OneDrive//Desktop//Demo1.xlsx",header=1)
df

,Name,Unnamed: 1,Email,Course
0,Hailey Antcliff,Hailey_Antcliff9757@yahoo.audio,Leadership,"Wednesday, December 14, 2022"
1,Harvey Reyes,Harvey_Reyes9354@voylg.directory,Analytics,"Friday, December 30, 2022"
2,Carina Stubbs,Carina_Stubbs8509@jh02o.org,Accounting,"Sunday, December 4, 2022"
3,NaN,Ramon_Redden905@1kmd3.club,Design and technology,"Wednesday, December 7, 2022"
4,NaN,Maya_Randall2939@lhp4j.meet,NaN,NaN
5,Matt Ashley,Maya Randall,Analytics,"Friday, December 30, 2022"
6,Freya Reynolds,Freya_Reynolds9608@bqkv0.site,Accounting,"Saturday, December 3, 2022"
7,Ronald Newton,Ronald_Newton1403@1kmd3.com,Design and technology,"Thursday, December 22, 2022"
8,Jack Hobbs,Jack_Hobbs4073@evyvh.auction,Design and technology,"Wednesday, December 7, 2022"

In [114]:
df.shape

(9, 4)

In [116]:
df.columns = ['Name', 'Email', 'Course', 'Date']
df

,Name,Email,Course,Date
0,Hailey Antcliff,Hailey_Antcliff9757@yahoo.audio,Leadership,"Wednesday, December 14, 2022"
1,Harvey Reyes,Harvey_Reyes9354@voylg.directory,Analytics,"Friday, December 30, 2022"
2,Carina Stubbs,Carina_Stubbs8509@jh02o.org,Accounting,"Sunday, December 4, 2022"
3,NaN,Ramon_Redden905@1kmd3.club,Design and technology,"Wednesday, December 7, 2022"
4,NaN,Maya_Randall2939@lhp4j.meet,NaN,NaN
5,Matt Ashley,Maya Randall,Analytics,"Friday, December 30, 2022"
6,Freya Reynolds,Freya_Reynolds9608@bqkv0.site,Accounting,"Saturday, December 3, 2022"
7,Ronald Newton,Ronald_Newton1403@1kmd3.com,Design and technology,"Thursday, December 22, 2022"
8,Jack Hobbs,Jack_Hobbs4073@evyvh.auction,Design and technology,"Wednesday, December 7, 2022"

In [128]:
df.fillna('not available')

,Name,Email,Course,Date
0,Hailey Antcliff,Hailey_Antcliff9757@yahoo.audio,Leadership,"Wednesday, December 14, 2022"
1,Harvey Reyes,Harvey_Reyes9354@voylg.directory,Analytics,"Friday, December 30, 2022"
2,Carina Stubbs,Carina_Stubbs8509@jh02o.org,Accounting,"Sunday, December 4, 2022"
3,not available,Ramon_Redden905@1kmd3.club,Design and technology,"Wednesday, December 7, 2022"
4,not available,Maya_Randall2939@lhp4j.meet,not available,not available
5,Matt Ashley,Maya Randall,Analytics,"Friday, December 30, 2022"
6,Freya Reynolds,Freya_Reynolds9608@bqkv0.site,Accounting,"Saturday, December 3, 2022"
7,Ronald Newton,Ronald_Newton1403@1kmd3.com,Design and technology,"Thursday, December 22, 2022"
8,Jack Hobbs,Jack_Hobbs4073@evyvh.auction,Design and technology,"Wednesday, December 7, 2022"

In [132]:
df['Course _name_upper']=df['Course'].fillna(" ").apply(lambda name: name.upper())
df

,Name,Email,Course,Date,Course _name_upper
0,Hailey Antcliff,Hailey_Antcliff9757@yahoo.audio,Leadership,"Wednesday, December 14, 2022",LEADERSHIP
1,Harvey Reyes,Harvey_Reyes9354@voylg.directory,Analytics,"Friday, December 30, 2022",ANALYTICS
2,Carina Stubbs,Carina_Stubbs8509@jh02o.org,Accounting,"Sunday, December 4, 2022",ACCOUNTING
3,NaN,Ramon_Redden905@1kmd3.club,Design and technology,"Wednesday, December 7, 2022",DESIGN AND TECHNOLOGY
4,NaN,Maya_Randall2939@lhp4j.meet,NaN,NaN,
5,Matt Ashley,Maya Randall,Analytics,"Friday, December 30, 2022",ANALYTICS
6,Freya Reynolds,Freya_Reynolds9608@bqkv0.site,Accounting,"Saturday, December 3, 2022",ACCOUNTING
7,Ronald Newton,Ronald_Newton1403@1kmd3.com,Design and technology,"Thursday, December 22, 2022",DESIGN AND TECHNOLOGY
8,Jack Hobbs,Jack_Hobbs4073@evyvh.auction,Design and technology,"Wednesday, December 7, 2022",DESIGN AND TECHNOLOGY